### ISSUE TITLE
Annotation information provides wrong offsets 

### ISSUE THREAD

**Issue by Kristober** [mideind/Yfirlestur#7]
If I make an API call with the text `Ég dreimi um að leita af myndinni` for example.

One of the annotations contains these values:

```json
{
    "code": "P_WRONG_PREP_AF",
    "detail": "Sögnin 'leita' tekur yfirleitt með sér forsetninguna 'að', ekki 'af'.",
    "end": 5,
    "end_char": 23,
    "references": [],
    "start": 4,
    "start_char": 15,
    "suggest": "leita að myndinni",
    "suggestlist": null,
    "text": "'leita af' á sennilega að vera 'leita að'"
}
```
Not being able to rely on the `start` and `end` offsets for the `suggest` makes this difficult to use.

It would help if `suggest` was `leita að` **or** `start` and `end` offsets covered the words that the suggestion is given for i.e. `start: 4` & `end: 6` in this case.

**Comment by vesteinn** [comment]
This looks like it is a bug in the underlying package [GreynirCorrect ](https://github.com/mideind/GreynirCorrect), we've made a note of it in our bug tracker for that package!

**Comment by Holado** [comment]
We have recently overhauled the spans for error annotations, to limit it as much as can be to the words that are changed. The rule fired here still had the old spans. This has been fixed and merged into master, so the spans and suggest values are limited to the 'að/af' tokens.
This simplifies some things, as an example in the sentence 'Ég dreimi um að leita ekki af myndinni.' it is preferable to limit the span to 'af' instead of 'leita ekki af'. The phrases can get rather long, so the approach of limiting the spans as much as possible was taken.

**Comment by Kristober** [comment]
I am still getting the exact same `suggest` as before, am I missing something?

**Comment by Holado** [comment]
The package `GreynirCorrect` has been updated on GitHub and PyPI. Are you using the Yfirlestur API? That was updated just now.
The output I get for this sentence using `diffchecker.py` in GreynirCorrect is the following:
```
Ég dreimi um að leita af myndinni
Mig dreymi um að leita að myndinni
000-000: P_WRONG_CASE_nf_þf Á líklega að vera 'Mig' | 'Ég' -> 'Mig' | None
001-001: S004   Orðið 'dreimi' var leiðrétt í 'dreymi' | 'dreimi' -> 'dreymi' | None
005-005: P_WRONG_PREP_AF 'leita af' á sennilega að vera 'leita að' | 'af' -> 'að' | None

```
As you can see, the span and suggest values for P_WRONG_PREP_AF are now limited to 'af'.

**Comment by Kristober** [comment]
Yes, I was using Yfirlestur, working as you described now, thanks!

**Comment by lumpidu** [comment]
@Holado : could you also backport these changes here into the repository ?

**Comment by Holado** [comment]
@lumpidu: Could you clarify? This repository? If you update the underlying GreynirCorrect package for the endpoint it should work.
